/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package emmanuelapp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Conecta-J
 */
public class Frame extends javax.swing.JFrame{
    
    static String BUSCAR = "BUSCANDO";
    static String GENERAR = "GENERAR";
    static String SALIDA = "SALIDA";
    static String XLS97 = "XLS97";
    static String XLS2010 = "XLS2010";
    
    public void Frame(){
        jButton_busq.setActionCommand(BUSCAR);
        jButton_procesa.setActionCommand(GENERAR);
    }
    
    public void setController(ControlEmmanuel c){
        jButton_busq.addActionListener(c);
        jButton_procesa.addActionListener(c);
        jButton_salida.addActionListener(c);
    }

    /**
     * Creates new form NewJFrame
     */
    public Frame() {
        initComponents();
        jButton_busq.setActionCommand(BUSCAR);
        jButton_procesa.setActionCommand(GENERAR);
        jButton_salida.setActionCommand(SALIDA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_format = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_resumen = new javax.swing.JTextArea();
        jButton_procesa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField_nomExcel = new javax.swing.JTextField();
        jRadioButton_97 = new javax.swing.JRadioButton();
        jRadioButton_2010 = new javax.swing.JRadioButton();
        jButton_salida = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField_dir = new javax.swing.JTextField();
        jButton_busq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

        jTextArea_resumen.setColumns(20);
        jTextArea_resumen.setRows(5);
        jScrollPane1.setViewportView(jTextArea_resumen);

        jButton_procesa.setText("Generar");
        jButton_procesa.setActionCommand("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_procesa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_procesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivo de salida"));

        buttonGroup_format.add(jRadioButton_97);
        jRadioButton_97.setText("Excel 97");

        buttonGroup_format.add(jRadioButton_2010);
        jRadioButton_2010.setText("Excel 2010");

        jButton_salida.setText("Ubicacion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField_nomExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_2010)
                .addGap(35, 35, 35)
                .addComponent(jButton_salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField_nomExcel)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton_97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton_2010, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_salida, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecciona Carpeta de facturas XML"));

        jButton_busq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emmanuelapp/busq.png"))); // NOI18N
        jButton_busq.setText("Buscar");
        jButton_busq.setActionCommand("NULL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_busq, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton_busq, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    public JButton getjButton_salida() {
        return jButton_salida;
    }

    public void setjButton_salida(JButton jButton_salida) {
        this.jButton_salida = jButton_salida;
    }

    public ButtonGroup getButtonGroup_format() {
        return buttonGroup_format;
    }

    public void setButtonGroup_format(ButtonGroup buttonGroup_format) {
        this.buttonGroup_format = buttonGroup_format;
    }

    public JButton getjButton_busq() {
        return jButton_busq;
    }

    public void setjButton_busq(JButton jButton_busq) {
        this.jButton_busq = jButton_busq;
    }

    public JButton getjButton_procesa() {
        return jButton_procesa;
    }

    public void setjButton_procesa(JButton jButton_procesa) {
        this.jButton_procesa = jButton_procesa;
    }

    public JTextArea getjTextArea_resumen() {
        return jTextArea_resumen;
    }

    public void setjTextArea_resumen(JTextArea jTextArea_resumen) {
        this.jTextArea_resumen = jTextArea_resumen;
    }

    public JTextField getjTextField_dir() {
        return jTextField_dir;
    }

    public void setjTextField_dir(JTextField jTextField_dir) {
        this.jTextField_dir = jTextField_dir;
    }

    public JTextField getjTextField_nomExcel() {
        return jTextField_nomExcel;
    }

    public void setjTextField_nomExcel(JTextField jTextField_nomExcel) {
        this.jTextField_nomExcel = jTextField_nomExcel;
    }

    public JRadioButton getjRadioButton_2010() {
        return jRadioButton_2010;
    }

    public void setjRadioButton_2010(JRadioButton jRadioButton_2010) {
        this.jRadioButton_2010 = jRadioButton_2010;
    }

    public JRadioButton getjRadioButton_97() {
        return jRadioButton_97;
    }

    public void setjRadioButton_97(JRadioButton jRadioButton_97) {
        this.jRadioButton_97 = jRadioButton_97;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_format;
    private javax.swing.JButton jButton_busq;
    private javax.swing.JButton jButton_procesa;
    private javax.swing.JButton jButton_salida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton_2010;
    private javax.swing.JRadioButton jRadioButton_97;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_resumen;
    private javax.swing.JTextField jTextField_dir;
    private javax.swing.JTextField jTextField_nomExcel;
    // End of variables declaration//GEN-END:variables

}
